# Generated by Django 4.2.6 on 2023-10-22 19:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="Имя"),
                ),
                (
                    "middle_name",
                    models.CharField(max_length=25, verbose_name="Отчество"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=25, verbose_name="Фамилия"),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="",
                        verbose_name="Фото",
                    ),
                ),
                ("sex", models.CharField(max_length=10, verbose_name="Пол")),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18)
                        ],
                        verbose_name="Возраст",
                    ),
                ),
                (
                    "contacts_phone",
                    models.CharField(max_length=15, verbose_name="Телефон"),
                ),
                (
                    "contacts_email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "contacts_other",
                    models.CharField(
                        max_length=150, verbose_name="Друой контакт"
                    ),
                ),
            ],
            options={
                "verbose_name": "Кандидат",
                "verbose_name_plural": "Кандидаты",
                "ordering": ["last_name"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Название курса",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=10,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип заянятости",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Опыт работы"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=20,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опыт работы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hard скилл",
                "verbose_name_plural": "Hard скиллы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=10,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Название курса",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Soft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soft скилл",
                "verbose_name_plural": "Soft скиллы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Направление специальности",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        verbose_name="График работы",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=10,
                        unique=True,
                        verbose_name="Уникальный слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "График работы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Отслеживаемый",
                "verbose_name_plural": "Отслеживаемые",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Кандидат для контакта",
                "verbose_name_plural": "Кандидаты для контакта",
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="course",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="employment_type",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.employmenttype",
                verbose_name="Тип занятости",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="experience",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.experience",
                verbose_name="Опыт работы",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="hards",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.hard",
                verbose_name="Хард скиллы",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="level",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.level",
                verbose_name="Уровень",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="softs",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.soft",
                verbose_name="Soft скиллы",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="specialization",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.specialization",
                verbose_name="Специализация",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="work_schedule",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.workschedule",
                verbose_name="График работы",
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("user", "candidate"), name="user_candidate"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("user", "candidate"), name="user_contact"
            ),
        ),
    ]
