# Generated by Django 4.2.6 on 2023-10-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="contacts_email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Почта"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="middle_name",
            field=models.CharField(max_length=150, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                max_length=150, unique=True, verbose_name="Уникальный слаг"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("Высшее", "Высшее"),
                    ("Магистр", "Магистр"),
                    ("Бакалавр", "Бакалавр"),
                    ("Неоконченное", "Неоконченное высшее"),
                    ("Кандидат", "Кандидат наук"),
                    ("Доктор наук", "Доктор наук"),
                    ("Не выбрано", "Не выбрано"),
                ],
                default="Высшее",
                max_length=30,
                verbose_name="Уровень образования",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="faculty",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Факультет"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="name",
            field=models.CharField(
                max_length=150,
                unique=True,
                verbose_name="Образование детально",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="name_university",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Учебное заведение"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="slug",
            field=models.SlugField(
                max_length=150, unique=True, verbose_name="Уникальный слаг"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="specialization",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Специализация"
            ),
        ),
        migrations.AlterField(
            model_name="experiencedetailed",
            name="name",
            field=models.CharField(
                max_length=150,
                unique=True,
                verbose_name="Опыт работы детальный",
            ),
        ),
        migrations.AlterField(
            model_name="experiencedetailed",
            name="post",
            field=models.CharField(max_length=100, verbose_name="Должность"),
        ),
        migrations.AlterField(
            model_name="experiencedetailed",
            name="slug",
            field=models.SlugField(
                max_length=100, unique=True, verbose_name="Уникальный слаг"
            ),
        ),
        migrations.AlterField(
            model_name="hardcands",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="hardcands",
            name="slug",
            field=models.SlugField(
                max_length=150, verbose_name="Уникальный слаг"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="slug",
            field=models.SlugField(
                max_length=30, unique=True, verbose_name="Уникальный слаг"
            ),
        ),
        migrations.AlterField(
            model_name="soft",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="soft",
            name="slug",
            field=models.SlugField(
                max_length=150, unique=True, verbose_name="Уникальный слаг"
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="name",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="specialization",
            name="slug",
            field=models.SlugField(
                max_length=150, unique=True, verbose_name="Уникальный слаг"
            ),
        ),
    ]
