# Generated by Django 4.2.6 on 2023-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="date_expiration",
            field=models.IntegerField(verbose_name="Дата окончания учебы"),
        ),
        migrations.AlterField(
            model_name="education",
            name="date_start",
            field=models.IntegerField(verbose_name="Дата начала учебы"),
        ),
        migrations.AlterField(
            model_name="experiencedetailed",
            name="date_expiration",
            field=models.IntegerField(verbose_name="Дата окончания работы"),
        ),
        migrations.AlterField(
            model_name="experiencedetailed",
            name="date_start",
            field=models.IntegerField(verbose_name="Дата начала работы"),
        ),
    ]
