# Generated by Django 4.2.6 on 2023-10-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="location",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Местонахождение"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="contacts_other",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Другой контакт"
            ),
        ),
    ]
