# Generated by Django 4.2.6 on 2023-10-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="course",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidates",
                to="candidates.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="education",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidates",
                to="candidates.education",
                verbose_name="Образование",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="employment_type",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidates",
                to="candidates.employmenttype",
                verbose_name="Тип занятости",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="candidates.experience",
                verbose_name="Опыт работы",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="experience_detailed",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidates",
                to="candidates.experiencedetailed",
                verbose_name="Детальный опыт работы",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="hards",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidates",
                to="candidates.hardcands",
                verbose_name="Хард скиллы",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="candidates/images/",
                verbose_name="Фото",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="level",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="candidates.level",
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="softs",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidates",
                to="candidates.soft",
                verbose_name="Soft скиллы",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="candidates.specialization",
                verbose_name="Специализация",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="work_schedule",
            field=models.ManyToManyField(
                blank=True,
                related_name="candidates",
                to="candidates.workschedule",
                verbose_name="График работы",
            ),
        ),
    ]
