# Generated by Django 4.2.6 on 2023-10-25 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to="candidates.candidate",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="course",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="detailed_experience",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.experiencedetailed",
                verbose_name="Детальный опыт работы",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="education",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.education",
                verbose_name="Образование",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="employment_type",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.employmenttype",
                verbose_name="Тип занятости",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="experience",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.experience",
                verbose_name="Опыт работы",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="hards",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.hardcands",
                verbose_name="Хард скиллы",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="level",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.level",
                verbose_name="Уровень",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="softs",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.soft",
                verbose_name="Soft скиллы",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="specialization",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.specialization",
                verbose_name="Специализация",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="work_schedule",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.workschedule",
                verbose_name="График работы",
            ),
        ),
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(
                fields=("user", "candidate"), name="user_candidate"
            ),
        ),
        migrations.AddConstraint(
            model_name="contact",
            constraint=models.UniqueConstraint(
                fields=("user", "candidate"), name="user_contact"
            ),
        ),
    ]
