# Generated by Django 4.2.6 on 2023-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidates",
            "0002_alter_candidate_course_alter_candidate_education_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="activity",
            field=models.CharField(
                choices=[
                    ("AC", "Активный"),
                    ("OH", "В ожидании"),
                    ("NA", "Не доступен"),
                ],
                default="NA",
                max_length=2,
                verbose_name="Статус соискателя",
            ),
        ),
    ]
