# Generated by Django 4.2.6 on 2023-10-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidates",
            "0002_candidate_location_alter_candidate_contacts_other",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="year_in_school",
            field=models.CharField(
                choices=[
                    ("AC", "Активный"),
                    ("OH", "В ожидании"),
                    ("NA", "Не доступен"),
                ],
                default="NA",
                max_length=2,
            ),
        ),
    ]
