# Generated by Django 4.2.6 on 2023-10-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_alter_education_date_expiration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="detailed_experience",
        ),
        migrations.AddField(
            model_name="candidate",
            name="detailed_experience",
            field=models.ManyToManyField(
                related_name="candidates",
                to="candidates.experiencedetailed",
                verbose_name="Детальный опыт работы",
            ),
        ),
    ]
