# Generated by Django 4.2.6 on 2023-10-25 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="date_expiration",
            new_name="date_graduation",
        ),
        migrations.RenameField(
            model_name="experiencedetailed",
            old_name="date_expiration",
            new_name="date_end",
        ),
    ]
