# Generated by Django 4.2.6 on 2023-10-24 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_remove_candidate_detailed_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="date_expiration",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Дата окончания учебы",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="date_start",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Дата начала учебы",
            ),
        ),
        migrations.AlterField(
            model_name="experiencedetailed",
            name="date_expiration",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Дата окончания работы",
            ),
        ),
        migrations.AlterField(
            model_name="experiencedetailed",
            name="date_start",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Дата начала работы",
            ),
        ),
    ]
