# Generated by Django 4.2.6 on 2023-10-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidates",
            "0003_rename_date_expiration_education_date_graduation_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="detailed_experience",
            new_name="experience_detailed",
        ),
        migrations.CreateModel(
            name="DetailInCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_in_candidate",
                        to="candidates.candidate",
                        verbose_name="Кандидат",
                    ),
                ),
                (
                    "experience_detailed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.experiencedetailed",
                        verbose_name="Детальный опыт работы",
                    ),
                ),
            ],
        ),
    ]
