# Generated by Django 4.2.6 on 2023-10-23 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_candidate_year_in_school"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="year_in_school",
            new_name="activity",
        ),
    ]
