# Generated by Django 4.2.6 on 2023-10-24 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0004_alter_education_date_expiration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["name"],
                "verbose_name": "Образование",
                "verbose_name_plural": "Образования",
            },
        ),
        migrations.AlterField(
            model_name="candidate",
            name="age",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Возраст",
            ),
        ),
    ]
