# Generated by Django 4.2.6 on 2023-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidates",
            "0004_rename_detailed_experience_candidate_experience_detailed_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="level",
            new_name="education_level",
        ),
        migrations.AddField(
            model_name="education",
            name="slug",
            field=models.SlugField(
                default=1,
                max_length=20,
                unique=True,
                verbose_name="Уникальный слаг",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experiencedetailed",
            name="slug",
            field=models.SlugField(
                default=1,
                max_length=20,
                unique=True,
                verbose_name="Уникальный слаг",
            ),
            preserve_default=False,
        ),
    ]
