# Generated by Django 4.2.6 on 2023-10-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0006_alter_candidate_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="education_level",
            field=models.CharField(
                choices=[
                    ("Высшее", "Высшее"),
                    ("Магистр", "Магистр"),
                    ("Бакалавр", "Бакалавр"),
                    ("Неоконченное", "Неоконченное высшее"),
                    ("Кандидат", "Кандидат наук"),
                    ("Доктор наук", "Доктор наук"),
                    ("Не выбрано", "Не выбрано"),
                ],
                default="Высшее",
                max_length=20,
                verbose_name="Уровень образования",
            ),
        ),
    ]
