const mockFilters = [
  { key: 0, label: 'Angular' },
  { key: 1, label: 'git' },
  { key: 2, label: 'HTML' },
  { key: 3, label: 'React' },
  { key: 4, label: 'vite' },
  { key: 5, label: 'Angular' },
  { key: 6, label: 'git' },
  { key: 7, label: 'HTML' },
  { key: 8, label: 'React' },
  { key: 9, label: 'vite' },
  { key: 10, label: 'Angular' },
  { key: 11, label: 'git' },
  { key: 12, label: 'HTML' },
  { key: 13, label: 'React' },
  { key: 14, label: 'vite' },
  { key: 15, label: 'Angular' },
  { key: 16, label: 'git' },
  { key: 17, label: 'HTML' },
  { key: 18, label: 'React' },
  { key: 19, label: 'vite' },
  { key: 20, label: 'Angular' },
  { key: 21, label: 'git' },
  { key: 22, label: 'HTML' },
  { key: 23, label: 'React' },
  { key: 24, label: 'vite' },
];
export const mockSpecialties = [
  { key: 0, label: 'Программирование' },
  { key: 1, label: 'Дизайн' },
  { key: 2, label: 'Анализ данных' },
  { key: 3, label: 'Маркетинг' },
  { key: 4, label: 'Менеджмент' },
];

export default mockFilters;
